# SPDX-FileCopyrightText: Copyright © 2025 hashcatHitman
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

[build]
rustflags = [
    "-Ctarget-cpu=native",
    # "-Clink-arg=-fuse-ld=mold",
    # "-Zthreads=8",
    # "-Zcrate-attr=feature(strict_provenance_lints,unqualified_local_imports)",
]

[future-incompat-report]
frequency = 'always'

[cargo-new]
vcs = "git"

# [http]
# ssl-version.min = "tlsv1.3"

[profile.release]
codegen-units = 1
strip = true
opt-level = 3
debug = false
lto = true
incremental = false

[profile.release.package."*"]
codegen-units = 1
strip = true
opt-level = 3
debug = false
incremental = false

[profile.release.build-override]
codegen-units = 1
strip = true
opt-level = 3
debug = false
incremental = false
