# SPDX-FileCopyrightText: © 2026 hashcatHitman
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

name: Workflow Scan

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]
  workflow_dispatch: {}

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  ZIZMOR_VERSION: 1.29.0

defaults:
  run:
    shell: bash

jobs:
  zizmor:
    name: Workflow Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Required for upload-sarif to upload SARIF files.
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install Rust
        run: rustup update stable && rustup default stable
      - name: Check cache for zizmor
        id: cache-zizmor
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.cargo/bin/zizmor
          key: zizmor-bin-${{ env.ZIZMOR_VERSION }}
      - if: ${{ steps.cache-zizmor.outputs.cache-hit != 'true' }}
        name: Install zizmor
        run: cargo install --locked --version ${ZIZMOR_VERSION} zizmor
      - name: Invoke zizmor
        run: zizmor --persona auditor --format=sarif . > zizmor_results.sarif
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@cdf488f595d80d6e07e03d4674febd5ab45fa938 # v4.37.9
        with:
          sarif_file: zizmor_results.sarif
          category: zizmor
